#include "MAIN.H"


char ready_to_transmit = 0, input_ready = -1;

void ASC0_vInit(void)
{

  ///  -----------------------------------------------------------------------
  ///  Configuration of the ASC0 Baud Rate Generator:
  ///  -----------------------------------------------------------------------
  ///  - the ASC0 module clock is 20 MHz
  ///  - required baud rate = 57.600 kbaud
  ///  - real baud rate     = 56.818 kbaud
  ///  - deviation          = -1.357 %

  S0BG           =  0x000A;      // load ASC0 baud rate time reload register

  ///  -----------------------------------------------------------------------
  ///  Configuration of the ASC0 Operation Mode:
  ///  -----------------------------------------------------------------------
  ///  - 8-bit data asychronous operation width one stop bit
  ///  - loopback mode is enabled
  ///  - receiver is enabled

  S0CON          =  0x0011;      // load ASC0 control register

  ///  -----------------------------------------------------------------------
  ///  Configuration of the used ASC0 Port Pins:
  ///  -----------------------------------------------------------------------
  ///  - P3.10 is used for ASC Transmit Data Output (TxD0)
  ///  - P3.11 is used for ASC Receive data Input (RxD0)

  P3   = (P3   & ~(uword)0x0400) | 0x0400;    //set data register
  DP3  = (DP3  & ~(uword)0x0400) | 0x0400;    //set direction register

  ///  -----------------------------------------------------------------------
  ///  Configuration of the used ASC0 Interrupts:
  ///  -----------------------------------------------------------------------
  ///  - transmit service request node configuration:
  ///  - transmit interrupt priority level (ILVL) = 7
  ///  - transmit interrupt group level (GLVL) = 1

  S0TIC          =  0x005D;     

  ///  - transmit buffer service request node configuration:
  ///  - transmit buffer interrupt priority level (ILVL) = 8
  ///  - transmit buffer interrupt group level (GLVL) = 1

  S0TBIC         =  0x0061;     

  S0RIC          =  0x0065;     

  S0CON         |=  0x8000;      // enable baud rate generator


} 

void ASC0_vSendData(uword uwData)
{
	// set flag to show that the serial tools abstraction layer cannot send any more data for now
	ready_to_transmit = -1;

	// actually put the byte to be set into the transmit buffer
	S0TBUF  = uwData;

} 

// get byte from the buffer
uword ASC0_uwGetData(void)
{
	// set input_ready to show that the byte has been read - used by the serial tools abstraction layer
	input_ready = -1;
	
	// return receive buffer register
	return(S0RBUF);
} 

// interrupt for when data has been transmitted. currently not used
void ASC0_viTx(void) interrupt S0TINT
{
	
}

void ASC0_viTxBuf(void) interrupt S0TBINT
{
	// reset flag to show that the board is ready to transmit
	ready_to_transmit = 0;
} 

// return flag that shows if ready to send data
char ASC0_cReadyToTransmit(void) {
	return ready_to_transmit;
}

// generated by DAvE
void ASC0_vReceiverOn(void)
{
  S0CON_S0REN = 1;               // enable the receiver
} 

char ASC0_cReadyToReceive(void) {
	// return whether there is an input waiting to be processed from serial
	return input_ready;
}

void ASC0_viRx(void) interrupt S0RINT
{
	// reset flag to show program if there is an input waiting to be processed
	input_ready = 0;

	// debug: show the value being sent over serial on LEDs
	IO_vWritePort(P2, S0RBUF);

} 
